#!/bin/bash
# =============================================================================
# config-env.sh — export build-config.mk values as shell variables
# =============================================================================
# Usage:  eval "$(./tools/config-env.sh)"
# Parses build-config.mk (generated by conf.sh --generate) and emits
# `export NAME=value` statements to stdout so shell consumers can source it.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_FILE="$SCRIPT_DIR/build-config.mk"

if [ ! -f "$CONFIG_FILE" ]; then
    echo "build-config.mk not found — run ./conf.sh --generate" >&2
    exit 1
fi

echo "# config-env: loaded from build-config.mk" >&2

# Match lines of the form:  NAME := value
# Skip comments (#) and blank lines. Export every value verbatim (yes/no,
# numbers, strings, FEATURE_FLAGS). %q produces a shell-safe quoted form so
# `eval "$(./tools/config-env.sh)"` is safe even for values with spaces.
config_line_regex='^([A-Z_]+) := (.*)$'
while IFS= read -r line; do
    case "$line" in
        ''|'#'*) continue ;;
    esac
    if [[ "$line" =~ $config_line_regex ]]; then
        name="${BASH_REMATCH[1]}"
        value="${BASH_REMATCH[2]}"
        printf 'export %s=%q\n' "$name" "$value"
    fi
done < "$CONFIG_FILE"
