theme=/usr/share/themes/default.theme
locale=/usr/share/locales/default.locale
keymap=/usr/share/keymaps/us.keymap
wallpaper=/usr/share/images/background/login.bmp
profile=/usr/share/images/profile/dog.bmp
DE=/bin/canopyde.elf
login_wallpaper=/usr/share/images/background/login.bmp
login_profile=/usr/share/images/profile/dog.bmp
places=/usr/share/desktop/places.conf
quick_paths=/usr/share/desktop/quick_paths.conf
mime=/usr/share/mime/mime.types
codecs=/usr/share/codecs
