Home Folder|/home/root|files
Session Config|/home/root/.session/.conf|files
Wallpaper: login|/usr/share/images/background/login.bmp|
Profile: dog|/usr/share/images/profile/dog.bmp|
Profile: cat|/usr/share/images/profile/cat.bmp|
Profile: fox|/usr/share/images/profile/fox.bmp|
