[Icon Theme]
Name=hicolor
Comment=Forest OS Freedesktop fallback icon theme
Hidden=true
Directories=scalable/apps,scalable/actions,scalable/devices,scalable/filesystems,scalable/mimetypes

[scalable/apps]
Size=48
Type=Scalable
MinSize=16
MaxSize=256
Context=Applications

[scalable/actions]
Size=48
Type=Scalable
MinSize=16
MaxSize=256
Context=Actions

[scalable/devices]
Size=48
Type=Scalable
MinSize=16
MaxSize=256
Context=Devices

[scalable/filesystems]
Size=48
Type=Scalable
MinSize=16
MaxSize=256
Context=FileSystems

[scalable/mimetypes]
Size=48
Type=Scalable
MinSize=16
MaxSize=256
Context=MimeTypes
