/home/root
/home/root/.session/.conf
/home/root/.session/notes.txt
/usr/bin/canopy_app_terminal.elf
/usr/bin/canopy_app_settings.elf
/usr/share/images/background/login.bmp
/usr/share/images/profile/dog.bmp
/usr/share/images/profile/cat.bmp
/etc/shadow
/var/log/boot.log
